### ISSUE TITLE
Release labourR 1.0.0

### ISSUE THREAD

**Issue by AleKoure** [AleKoure/labourR#1]
Prepare for release: 
 
* [x] Check that description is informative 
* [x] Check licensing of included files 
* [x] `usethis::use_cran_comments()` 
* [x] `devtools::check()` 
* [x] `devtools::check_win_devel()` 
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `rhub::check_with_sanitizers()`
* [x] `rhub::check_for_cran()` 
* [x] Polish pkgdown reference index 
* [x] Draft blog post 
 
Submit to CRAN: 
 
* [x] `usethis::use_version('major')` 
* [x] Update `cran-comments.md` 
* [x] `devtools::submit_cran()` 
* [x] Approve email 
 
Wait for CRAN... 
 
* [x] Accepted :tada: 
* [x] `usethis::use_github_release()` 
* [x] `usethis::use_dev_version()` 
* [x] `usethis::use_news_md()` 
* [x] Update install instructions in README 
* [x] Finish blog post 
* [x] Tweet 
* [x] Add link to blog post in pkgdown news menu

**Comment by AleKoure** [comment]
After normalization rounding is needed for tfidf numerical statistic to reduce the size of the data. Also, character columns are turned to factors and `xz` compression used.

**Comment by AleKoure** [comment]
sudo apt-get install texinfo to build manual locally

**Comment by AleKoure** [comment]
rhub::check(
     platform="windows-x86_64-devel",
     env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always")

builds ok

**Comment by AleKoure** [comment]
for rhub::check_for_cran() comment in cran-comments.md

**Comment by AleKoure** [comment]
Error: Vignette re-building failed. rmarkdown must be included in Description suggests.

**Comment by peterthunder** [comment]
```
Thanks, please replace \dontrun{} by \donttest{} or unwap the examples if they can be executed in less than 5 sec per Rd-file.

If there are references describing the (theoretical background of) methods in your package, please add these in the Description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
with no space after 'doi:', 'arXiv:' and angle brackets for auto-linking.

Please fix and resubmit.
```

Added 3 papers in the DESCRIPTION file. Removed donttrun wrap around examples.
